const dummyData = [
    {
        id: 1,
        no_tiket: "TKT-00001",
        cid: "1234567890",
        nama: "John Doe",
        alamat: "Jl. Contoh No. 1, Jakarta",
        no_hp: "081234567890",
        komplain: "Tidak ada kabel HDMI",
        pelapor: "John Doe",
        tanggal_laporan: "2023-10-01",
        status: "Open",
        jenis_gangguan: "Hardware",
        jenis_perbaikan: "",
        lokasi_odp: "",
        lokasi_closure: "",
        jarak_kabel: "",
        redaman_terakhir: "",
        nama_wifi: "",
        password_wifi: "",
        keterangan: "",
        tanggal_perbaikan: "",
        teknisi: "",
        createdAt: "2023-10-01",
        updatedAt: "2023-10-02"
    },
    {
        id: 2,
        no_tiket: "TKT-00002",
        cid: "0987654321",
        nama: "Jane Smith",
        alamat: "Jl. Contoh No. 2, Bandung",
        no_hp: "082345678901",
        komplain: "Internet lambat",
        pelapor: "Jane Smith",
        tanggal_laporan: "2023-10-02",
        status: "Open",
        jenis_gangguan: "Network",
        jenis_perbaikan: "Upgrade",
        lokasi_odp: "ODP 1",
        lokasi_closure: "Location A",
        jarak_kabel: "50m",
        redaman_terakhir: "10dB",
        nama_wifi: "WiFi-Jane",
        password_wifi: "password123",
        keterangan: "Perbaikan selesai",
        tanggal_perbaikan: "2023-10-03",
        teknisi: "Teknisi A",
        createdAt: "2023-10-02",
        updatedAt: "2023-10-03"
    },
    {
        id: 3,
        no_tiket: "TKT-00003",
        cid: "1122334455",
        nama: "Alice Johnson",
        alamat: "Jl. Contoh No. 3, Surabaya",
        no_hp: "083456789012",
        komplain: "Tidak bisa terhubung ke WiFi",
        pelapor: "Alice Johnson",
        tanggal_laporan: "2023-10-03",
        status: "Open",
        jenis_gangguan: "Software",
        jenis_perbaikan: "",
        lokasi_odp: "",
        lokasi_closure: "",
        jarak_kabel: "",
        redaman_terakhir: "",
        nama_wifi: "",
        password_wifi: "",
        keterangan: "",
        tanggal_perbaikan: "",
        teknisi: "",
        createdAt: "2023-10-03",
        updatedAt: "2023-10-04"
    },
    {
        id: 4,
        no_tiket: "TKT-00004",
        cid: "2233445566",
        nama: "Bob Brown",
        alamat: "Jl. Contoh No. 4, Medan",
        no_hp: "084567890123",
        komplain: "Koneksi terputus-putus",
        pelapor: "Bob Brown",
        tanggal_laporan: "2023-10-04",
        status: "Close",
        jenis_gangguan: "Network",
        jenis_perbaikan: "Reset",
        lokasi_odp: "ODP 2",
        lokasi_closure: "Location B",
        jarak_kabel: "30m",
        redaman_terakhir: "5dB",
        nama_wifi: "WiFi-Bob",
        password_wifi: "bobpassword",
        keterangan: "Perbaikan selesai",
        tanggal_perbaikan: "2023-10-05",
        teknisi: "Teknisi B",
        createdAt: "2023-10-04",
        updatedAt: "2023-10-05"
    },
    {
        id: 5,
        no_tiket: "TKT-00005",
        cid: "3344556677",
        nama: "Charlie Davis",
        alamat: "Jl. Contoh No. 5, Yogyakarta",
        no_hp: "085678901234",
        komplain: "Tidak ada sinyal",
        pelapor: "Charlie Davis",
        tanggal_laporan: "2023-10-05",
        status: "Open",
        jenis_gangguan: "Hardware",
        jenis_perbaikan: "",
        lokasi_odp: "",
        lokasi_closure: "",
        jarak_kabel: "",
        redaman_terakhir: "",
        nama_wifi: "",
        password_wifi: "",
        keterangan: "",
        tanggal_perbaikan: "",
        teknisi: "",
        createdAt: "2023-10-05",
        updatedAt: "2023-10-06"
    },
    {
        id: 6,
        no_tiket: "TKT-00006",
        cid: "4455667788",
        nama: "Diana Evans",
        alamat: "Jl. Contoh No. 6, Bali",
        no_hp: "086789012345",
        komplain: "WiFi sering terputus",
        pelapor: "Diana Evans",
        tanggal_laporan: "2023-10-06",
        status: "Close",
        jenis_gangguan: "Network",
        jenis_perbaikan: "Perbaikan kabel",
        lokasi_odp: "ODP 3",
        lokasi_closure: "Location C",
        jarak_kabel: "20m",
        redaman_terakhir: "8dB",
        nama_wifi: "WiFi-Diana",
        password_wifi: "dianapassword",
        keterangan: "Perbaikan selesai",
        tanggal_perbaikan: "2023-10-07",
        teknisi: "Teknisi C",
        createdAt: "2023-10-06",
        updatedAt: "2023-10-07"
    },
    {
        id: 7,
        no_tiket: "TKT-00007",
        cid: "5566778899",
        nama: "Eve Foster",
        alamat: "Jl. Contoh No. 7, Jakarta",
        no_hp: "087890123456",
        komplain: "Koneksi lambat",
        pelapor: "Eve Foster",
        tanggal_laporan: "2023-10-07",
        status: "Open",
        jenis_gangguan: "Software",
        jenis_perbaikan: "",
        lokasi_odp: "",
        lokasi_closure: "",
        jarak_kabel: "",
        redaman_terakhir: "",
        nama_wifi: "",
        password_wifi: "",
        keterangan: "",
        tanggal_perbaikan: "",
        teknisi: "",
        createdAt: "2023-10-07",
        updatedAt: "2023-10-08"
    },
    {
        id: 8,
        no_tiket: "TKT-00008",
        cid: "6677889900",
        nama: "Frank Green",
        alamat: "Jl. Contoh No. 8, Bandung",
        no_hp: "088901234567",
        komplain: "Tidak bisa login",
        pelapor: "Frank Green",
        tanggal_laporan: "2023-10-08",
        status: "Close",
        jenis_gangguan: "Software",
        jenis_perbaikan: "Reset password",
        lokasi_odp: "ODP 4",
        lokasi_closure: "Location D",
        jarak_kabel: "",
        redaman_terakhir: "",
        nama_wifi: "WiFi-Frank",
        password_wifi: "frankpassword",
        keterangan: "Perbaikan selesai",
        tanggal_perbaikan: "2023-10-09",
        teknisi: "Teknisi D",
        createdAt: "2023-10-08",
        updatedAt: "2023-10-09"
    },
    {
        id: 9,
        no_tiket: "TKT-00009",
        cid: "7788990011",
        nama: "Grace Lee",
        alamat: "Jl. Contoh No. 9, Surabaya",
        no_hp: "089012345678",
        komplain: "Sinyal lemah",
        pelapor: "Grace Lee",
        tanggal_laporan: "2023-10-09",
        status: "Open",
        jenis_gangguan: "Hardware",
        jenis_perbaikan: "",
        lokasi_odp: "",
        lokasi_closure: "",
        jarak_kabel: "",
        redaman_terakhir: "",
        nama_wifi: "",
        password_wifi: "",
        keterangan: "",
        tanggal_perbaikan: "",
        teknisi: "",
        createdAt: "2023-10-09",
        updatedAt: "2023-10-10"
    },
    {
        id: 10,
        no_tiket: "TKT-00010",
        cid: "8899001122",
        nama: "Henry White",
        alamat: "Jl. Contoh No. 10, Yogyakarta",
        no_hp: "090123456789",
        komplain: "Tidak ada internet",
        pelapor: "Henry White",
        tanggal_laporan: "2023-10-10",
        status: "Close",
        jenis_gangguan: "Network",
        jenis_perbaikan: "Perbaikan jaringan",
        lokasi_odp: "ODP 5",
        lokasi_closure: "Location E",
        jarak_kabel: "15m",
        redaman_terakhir: "6dB",
        nama_wifi: "WiFi-Henry",
        password_wifi: "henrypassword",
        keterangan: "Perbaikan selesai",
        tanggal_perbaikan: "2023-10-11",
        teknisi: "Teknisi E",
        createdAt: "2023-10-10",
        updatedAt: "2023-10-11"
    },
    {
        id: 11,
        no_tiket: "TKT-00011",
        cid: "9900112233",
        nama: "Ivy Brown",
        alamat: "Jl. Contoh No. 11, Jakarta",
        no_hp: "091234567890",
        komplain: "Koneksi terputus",
        pelapor: "Ivy Brown",
        tanggal_laporan: "2023-10-11",
        status: "Open",
        jenis_gangguan: "Network",
        jenis_perbaikan: "",
        lokasi_odp: "",
        lokasi_closure: "",
        jarak_kabel: "",
        redaman_terakhir: "",
        nama_wifi: "",
        password_wifi: "",
        keterangan: "",
        tanggal_perbaikan: "",
        teknisi: "",
        createdAt: "2023-10-11",
        updatedAt: "2023-10-12"
    },
    {
        id: 12,
        no_tiket: "TKT-00012",
        cid: "1011121314",
        nama: "Jack Black",
        alamat: "Jl. Contoh No. 12, Bandung",
        no_hp: "092345678901",
        komplain: "Internet lambat",
        pelapor: "Jack Black",
        tanggal_laporan: "2023-10-12",
        status: "Open",
        jenis_gangguan: "Network",
        jenis_perbaikan: "Upgrade",
        lokasi_odp: "ODP 6",
        lokasi_closure: "Location F",
        jarak_kabel: "40m",
        redaman_terakhir: "7dB",
        nama_wifi: "WiFi-Jack",
        password_wifi: "jackpassword",
        keterangan: "Perbaikan sedang berlangsung",
        tanggal_perbaikan: "",
        teknisi: "",
        createdAt: "2023-10-12",
        updatedAt: "2023-10-13"
    },
    {
        id: 13,
        no_tiket: "TKT-00013",
        cid: "1415161718",
        nama: "Lily White",
        alamat: "Jl. Contoh No. 13, Surabaya",
        no_hp: "093456789012",
        komplain: "Tidak bisa terhubung ke WiFi",
        pelapor: "Lily White",
        tanggal_laporan: "2023-10-13",
        status: "Close",
        jenis_gangguan: "Software",
        jenis_perbaikan: "Reset password",
        lokasi_odp: "ODP 7",
        lokasi_closure: "Location G",
        jarak_kabel: "",
        redaman_terakhir: "",
        nama_wifi: "WiFi-Lily",
        password_wifi: "lilypassword",
        keterangan: "Perbaikan selesai",
        tanggal_perbaikan: "2023-10-14",
        teknisi: "Teknisi F",
        createdAt: "2023-10-13",
        updatedAt: "2023-10-14"
    },
    {
        id: 14,
        no_tiket: "TKT-00014",
        cid: "1920212223",
        nama: "Mia Green",
        alamat: "Jl. Contoh No. 14, Yogyakarta",
        no_hp: "094567890123",
        komplain: "Sinyal lemah",
        pelapor: "Mia Green",
        tanggal_laporan: "2023-10-14",
        status: "Open",
        jenis_gangguan: "Hardware",
        jenis_perbaikan: "",
        lokasi_odp: "",
        lokasi_closure: "",
        jarak_kabel: "",
        redaman_terakhir: "",
        nama_wifi: "",
        password_wifi: "",
        keterangan: "",
        tanggal_perbaikan: "",
        teknisi: "",
        createdAt: "2023-10-14",
        updatedAt: "2023-10-15"
    },
    {
        id: 15,
        no_tiket: "TKT-00015",
        cid: "2425262728",
        nama: "Noah Blue",
        alamat: "Jl. Contoh No. 15, Jakarta",
        no_hp: "095678901234",
        komplain: "Koneksi terputus-putus",
        pelapor: "Noah Blue",
        tanggal_laporan: "2023-10-15",
        status: "Close",
        jenis_gangguan: "Network",
        jenis_perbaikan: "Reset",
        lokasi_odp: "ODP 8",
        lokasi_closure: "Location H",
        jarak_kabel: "25m",
        redaman_terakhir: "4dB",
        nama_wifi: "WiFi-Noah",
        password_wifi: "noahpassword",
        keterangan: "Perbaikan selesai",
        tanggal_perbaikan: "2023-10-16",
        teknisi: "Teknisi G",
        createdAt: "2023-10-15",
        updatedAt: "2023-10-16"
    },
    {
        id: 16,
        no_tiket: "TKT-00016",
        cid: "2930313233",
        nama: "Olivia Red",
        alamat: "Jl. Contoh No. 16, Bandung",
        no_hp: "096789012345",
        komplain: "Tidak ada internet",
        pelapor: "Olivia Red",
        tanggal_laporan: "2023-10-16",
        status: "Open",
        jenis_gangguan: "Network",
        jenis_perbaikan: "",
        lokasi_odp: "",
        lokasi_closure: "",
        jarak_kabel: "",
        redaman_terakhir: "",
        nama_wifi: "",
        password_wifi: "",
        keterangan: "",
        tanggal_perbaikan: "",
        teknisi: "",
        createdAt: "2023-10-16",
        updatedAt: "2023-10-17"
    },
    {
        id: 17,
        no_tiket: "TKT-00017",
        cid: "3435363738",
        nama: "Peter Grey",
        alamat: "Jl. Contoh No. 17, Surabaya",
        no_hp: "097890123456",
        komplain: "WiFi sering terputus",
        pelapor: "Peter Grey",
        tanggal_laporan: "2023-10-17",
        status: "Close",
        jenis_gangguan: "Software",
        jenis_perbaikan: "Perbaikan kabel",
        lokasi_odp: "ODP 9",
        lokasi_closure: "Location I",
        jarak_kabel: "10m",
        redaman_terakhir: "3dB",
        nama_wifi: "WiFi-Peter",
        password_wifi: "peterpassword",
        keterangan: "Perbaikan selesai",
        tanggal_perbaikan: "2023-10-18",
        teknisi: "Teknisi H",
        createdAt: "2023-10-17",
        updatedAt: "2023-10-18"
    },
    {
        id: 18,
        no_tiket: "TKT-00018",
        cid: "3940414243",
        nama: "Quinn Black",
        alamat: "Jl. Contoh No. 18, Yogyakarta",
        no_hp: "098901234567",
        komplain: "Koneksi lambat",
        pelapor: "Quinn Black",
        tanggal_laporan: "2023-10-18",
        status: "Open",
        jenis_gangguan: "Network",
        jenis_perbaikan: "",
        lokasi_odp: "",
        lokasi_closure: "",
        jarak_kabel: "",
        redaman_terakhir: "",
        nama_wifi: "",
        password_wifi: "",
        keterangan: "",
        tanggal_perbaikan: "",
        teknisi: "",
        createdAt: "2023-10-18",
        updatedAt: "2023-10-19"
    },
    {
        id: 19,
        no_tiket: "TKT-00019",
        cid: "4445464748",
        nama: "Riley White",
        alamat: "Jl. Contoh No. 19, Jakarta",
        no_hp: "099012345678",
        komplain: "Tidak bisa login",
        pelapor: "Riley White",
        tanggal_laporan: "2023-10-19",
        status: "Close",
        jenis_gangguan: "Software",
        jenis_perbaikan: "Reset password",
        lokasi_odp: "ODP 10",
        lokasi_closure: "Location J",
        jarak_kabel: "",
        redaman_terakhir: "",
        nama_wifi: "WiFi-Riley",
        password_wifi: "riley123",
        keterangan: "Perbaikan selesai",
        tanggal_perbaikan: "2023-10-20",
        teknisi: "Teknisi I",
        createdAt: "2023-10-19",
        updatedAt: "2023-10-20"
    },
    {
        id: 20,
        no_tiket: "TKT-00020",
        cid: "4949505152",
        nama: "Sophia Green",
        alamat: "Jl. Contoh No. 20, Bandung",
        no_hp: "100123456789",
        komplain: "Sinyal lemah",
        pelapor: "Sophia Green",
        tanggal_laporan: "2023-10-20",
        status: "Open",
        jenis_gangguan: "Hardware",
        jenis_perbaikan: "",
        lokasi_odp: "",
        lokasi_closure: "",
        jarak_kabel: "",
        redaman_terakhir: "",
        nama_wifi: "",
        password_wifi: "",
        keterangan: "",
        tanggal_perbaikan: "",
        teknisi: "",
        createdAt: "2023-10-20",
        updatedAt: "2023-10-21"
    },
    {
        id: 21,
        no_tiket: "TKT-00021",
        cid: "5152535455",
        nama: "Thomas Blue",
        alamat: "Jl. Contoh No. 21, Surabaya",
        no_hp: "101234567890",
        komplain: "Koneksi terputus-putus",
        pelapor: "Thomas Blue",
        tanggal_laporan: "2023-10-21",
        status: "Close",
        jenis_gangguan: "Network",
        jenis_perbaikan: "Reset",
        lokasi_odp: "ODP 11",
        lokasi_closure: "Location K",
        jarak_kabel: "35m",
        redaman_terakhir: "5dB",
        nama_wifi: "WiFi-Thomas",
        password_wifi: "thomaspassword",
        keterangan: "Perbaikan selesai",
        tanggal_perbaikan: "2023-10-22",
        teknisi: "Teknisi J",
        createdAt: "2023-10-21",
        updatedAt: "2023-10-22"
    },
    {
        id: 22,
        no_tiket: "TKT-00022",
        cid: "5657585960",
        nama: "Uma Red",
        alamat: "Jl. Contoh No. 22, Yogyakarta",
        no_hp: "102345678901",
        komplain: "Tidak ada internet",
        pelapor: "Uma Red",
        tanggal_laporan: "2023-10-22",
        status: "Open",
        jenis_gangguan: "Network",
        jenis_perbaikan: "",
        lokasi_odp: "",
        lokasi_closure: "",
        jarak_kabel: "",
        redaman_terakhir: "",
        nama_wifi: "",
        password_wifi: "",
        keterangan: "",
        tanggal_perbaikan: "",
        teknisi: "",
        createdAt: "2023-10-22",
        updatedAt: "2023-10-23"
    },
    {
        id: 23,
        no_tiket: "TKT-00023",
        cid: "6162636465",
        nama: "Victor Black",
        alamat: "Jl. Contoh No. 23, Jakarta",
        no_hp: "103456789012",
        komplain: "Koneksi lambat",
        pelapor: "Victor Black",
        tanggal_laporan: "2023-10-23",
        status: "Close",
        jenis_gangguan: "Software",
        jenis_perbaikan: "Reset password",
        lokasi_odp: "ODP 12",
        lokasi_closure: "Location L",
        jarak_kabel: "",
        redaman_terakhir: "",
        nama_wifi: "WiFi-Victor",
        password_wifi: "victorpassword",
        keterangan: "Perbaikan selesai",
        tanggal_perbaikan: "2023-10-24",
        teknisi: "Teknisi K",
        createdAt: "2023-10-23",
        updatedAt: "2023-10-24"
    },
    {
        id: 24,
        no_tiket: "TKT-00024",
        cid: "6667686970",
        nama: "Wendy Green",
        alamat: "Jl. Contoh No. 24, Bandung",
        no_hp: "104567890123",
        komplain: "Tidak bisa login",
        pelapor: "Wendy Green",
        tanggal_laporan: "2023-10-24",
        status: "Open",
        jenis_gangguan: "Software",
        jenis_perbaikan: "",
        lokasi_odp: "",
        lokasi_closure: "",
        jarak_kabel: "",
        redaman_terakhir: "",
        nama_wifi: "",
        password_wifi: "",
        keterangan: "",
        tanggal_perbaikan: "",
        teknisi: "",
        createdAt: "2023-10-24",
        updatedAt: "2023-10-25"
    },
    {
        id: 25,
        no_tiket: "TKT-00025",
        cid: "7071727374",
        nama: "Xander Blue",
        alamat: "Jl. Contoh No. 25, Surabaya",
        no_hp: "105678901234",
        komplain: "Sinyal lemah",
        pelapor: "Xander Blue",
        tanggal_laporan: "2023-10-25",
        status: "Close",
        jenis_gangguan: "Network",
        jenis_perbaikan: "Perbaikan jaringan",
        lokasi_odp: "ODP 13",
        lokasi_closure: "Location M",
        jarak_kabel: "20m",
        redaman_terakhir: "6dB",
        nama_wifi: "WiFi-Xander",
        password_wifi: "xanderpassword",
        keterangan: "Perbaikan selesai",
        tanggal_perbaikan: "2023-10-26",
        teknisi: "Teknisi L",
        createdAt: "2023-10-25",
        updatedAt: "2023-10-26"
    },
    {
        id: 26,
        no_tiket: "TKT-00026",
        cid: "7576777879",
        nama: "Yara Red",
        alamat: "Jl. Contoh No. 26, Yogyakarta",
        no_hp: "106789012345",
        komplain: "Koneksi terputus-putus",
        pelapor: "Yara Red",
        tanggal_laporan: "2023-10-26",
        status: "Open",
        jenis_gangguan: "Hardware",
        jenis_perbaikan: "",
        lokasi_odp: "",
        lokasi_closure: "",
        jarak_kabel: "",
        redaman_terakhir: "",
        nama_wifi: "",
        password_wifi: "",
        keterangan: "",
        tanggal_perbaikan: "",
        teknisi: "",
        createdAt: "2023-10-26",
        updatedAt: "2023-10-27"
    },
    {
        id: 27,
        no_tiket: "TKT-00027",
        cid: "8081828384",
        nama: "Zane Black",
        alamat: "Jl. Contoh No. 27, Jakarta",
        no_hp: "107890123456",
        komplain: "Internet lambat",
        pelapor: "Zane Black",
        tanggal_laporan: "2023-10-27",
        status: "Close",
        jenis_gangguan: "Network",
        jenis_perbaikan: "Reset",
        lokasi_odp: "ODP 14",
        lokasi_closure: "Location N",
        jarak_kabel: "15m",
        redaman_terakhir: "4dB",
        nama_wifi: "WiFi-Zane",
        password_wifi: "zane123",
        keterangan: "Perbaikan selesai",
        tanggal_perbaikan: "2023-10-28",
        teknisi: "Teknisi M",
        createdAt: "2023-10-27",
        updatedAt: "2023-10-28"
    },
    {
        id: 28,
        no_tiket: "TKT-00028",
        cid: "8586878889",
        nama: "Ava Green",
        alamat: "Jl. Contoh No. 28, Bandung",
        no_hp: "108901234567",
        komplain: "Tidak bisa login",
        pelapor: "Ava Green",
        tanggal_laporan: "2023-10-28",
        status: "Open",
        jenis_gangguan: "Software",
        jenis_perbaikan: "",
        lokasi_odp: "",
        lokasi_closure: "",
        jarak_kabel: "",
        redaman_terakhir: "",
        nama_wifi: "",
        password_wifi: "",
        keterangan: "",
        tanggal_perbaikan: "",
        teknisi: "",
        createdAt: "2023-10-28",
        updatedAt: "2023-10-29"
    },
    {
        id: 29,
        no_tiket: "TKT-00029",
        cid: "9091929394",
        nama: "Liam Blue",
        alamat: "Jl. Contoh No. 29, Surabaya",
        no_hp: "109012345678",
        komplain: "Sinyal lemah",
        pelapor: "Liam Blue",
        tanggal_laporan: "2023-10-29",
        status: "Close",
        jenis_gangguan: "Network",
        jenis_perbaikan: "Perbaikan jaringan",
        lokasi_odp: "ODP 15",
        lokasi_closure: "Location O",
        jarak_kabel: "10m",
        redaman_terakhir: "3dB",
        nama_wifi: "WiFi-Liam",
        password_wifi: "liam123",
        keterangan: "Perbaikan selesai",
        tanggal_perbaikan: "2023-10-30",
        teknisi: "Teknisi N",
        createdAt: "2023-10-29",
        updatedAt: "2023-10-30"
    },
    {
        id: 30,
        no_tiket: "TKT-00030",
        cid: "9495969798",
        nama: "Mason Red",
        alamat: "Jl. Contoh No. 30, Yogyakarta",
        no_hp: "110123456789",
        komplain: "Koneksi terputus-putus",
        pelapor: "Mason Red",
        tanggal_laporan: "2023-10-30",
        status: "Open",
        jenis_gangguan: "Hardware",
        jenis_perbaikan: "",
        lokasi_odp: "",
        lokasi_closure: "",
        jarak_kabel: "",
        redaman_terakhir: "",
        nama_wifi: "",
        password_wifi: "",
        keterangan: "",
        tanggal_perbaikan: "",
        teknisi: "",
        createdAt: "2023-10-30",
        updatedAt: "2023-10-31"
    },
    {
        id: 31,
        no_tiket: "TKT-00031",
        cid: "1011121314",
        nama: "Nora Green",
        alamat: "Jl. Contoh No. 31, Jakarta",
        no_hp: "111234567890",
        komplain: "Internet lambat",
        pelapor: "Nora Green",
        tanggal_laporan: "2023-10-31",
        status: "Close",
        jenis_gangguan: "Network",
        jenis_perbaikan: "Reset",
        lokasi_odp: "ODP 16",
        lokasi_closure: "Location P",
        jarak_kabel: "20m",
        redaman_terakhir: "5dB",
        nama_wifi: "WiFi-Nora",
        password_wifi: "norapassword",
        keterangan: "Perbaikan selesai",
        tanggal_perbaikan: "2023-11-01",
        teknisi: "Teknisi O",
        createdAt: "2023-10-31",
        updatedAt: "2023-11-01"
    },
    {
        id: 32,
        no_tiket: "TKT-00032",
        cid: "1314151617",
        nama: "Oscar Blue",
        alamat: "Jl. Contoh No. 32, Bandung",
        no_hp: "112345678901",
        komplain: "Tidak bisa login",
        pelapor: "Oscar Blue",
        tanggal_laporan: "2023-11-01",
        status: "Open",
        jenis_gangguan: "Software",
        jenis_perbaikan: "",
        lokasi_odp: "",
        lokasi_closure: "",
        jarak_kabel: "",
        redaman_terakhir: "",
        nama_wifi: "",
        password_wifi: "",
        keterangan: "",
        tanggal_perbaikan: "",
        teknisi: "",
        createdAt: "2023-11-01",
        updatedAt: "2023-11-02"
    },
    {
        id: 33,
        no_tiket: "TKT-00033",
        cid: "1718192021",
        nama: "Piper Red",
        alamat: "Jl. Contoh No. 33, Surabaya",
        no_hp: "113456789012",
        komplain: "Sinyal lemah",
        pelapor: "Piper Red",
        tanggal_laporan: "2023-11-02",
        status: "Close",
        jenis_gangguan: "Network",
        jenis_perbaikan: "Perbaikan jaringan",
        lokasi_odp: "ODP 17",
        lokasi_closure: "Location Q",
        jarak_kabel: "15m",
        redaman_terakhir: "4dB",
        nama_wifi: "WiFi-Piper",
        password_wifi: "piperpassword",
        keterangan: "Perbaikan selesai",
        tanggal_perbaikan: "2023-11-03",
        teknisi: "Teknisi P",
        createdAt: "2023-11-02",
        updatedAt: "2023-11-03"
    },
    {
        id: 34,
        no_tiket: "TKT-00034",
        cid: "2122232425",
        nama: "Quincy Green",
        alamat: "Jl. Contoh No. 34, Yogyakarta",
        no_hp: "114567890123",
        komplain: "Koneksi terputus-putus",
        pelapor: "Quincy Green",
        tanggal_laporan: "2023-11-03",
        status: "Open",
        jenis_gangguan: "Hardware",
        jenis_perbaikan: "",
        lokasi_odp: "",
        lokasi_closure: "",
        jarak_kabel: "",
        redaman_terakhir: "",
        nama_wifi: "",
        password_wifi: "",
        keterangan: "",
        tanggal_perbaikan: "",
        teknisi: "",
        createdAt: "2023-11-03",
        updatedAt: "2023-11-04"
    },
    {
        id: 35,
        no_tiket: "TKT-00035",
        cid: "2627282930",
        nama: "Ryder Blue",
        alamat: "Jl. Contoh No. 35, Jakarta",
        no_hp: "115678901234",
        komplain: "Internet lambat",
        pelapor: "Ryder Blue",
        tanggal_laporan: "2023-11-04",
        status: "Close",
        jenis_gangguan: "Network",
        jenis_perbaikan: "Reset",
        lokasi_odp: "ODP 18",
        lokasi_closure: "Location R",
        jarak_kabel: "20m",
        redaman_terakhir: "5dB",
        nama_wifi: "WiFi-Ryder",
        password_wifi: "ryderpassword",
        keterangan: "Perbaikan selesai",
        tanggal_perbaikan: "2023-11-05",
        teknisi: "Teknisi Q",
        createdAt: "2023-11-04",
        updatedAt: "2023-11-05"
    },
    {
        id: 36,
        no_tiket: "TKT-00036",
        cid: "3132333435",
        nama: "Sophie Red",
        alamat: "Jl. Contoh No. 36, Bandung",
        no_hp: "116789012345",
        komplain: "Tidak bisa login",
        pelapor: "Sophie Red",
        tanggal_laporan: "2023-11-05",
        status: "Open",
        jenis_gangguan: "Software",
        jenis_perbaikan: "",
        lokasi_odp: "",
        lokasi_closure: "",
        jarak_kabel: "",
        redaman_terakhir: "",
        nama_wifi: "",
        password_wifi: "",
        keterangan: "",
        tanggal_perbaikan: "",
        teknisi: "",
        createdAt: "2023-11-05",
        updatedAt: "2023-11-06"
    },
    {
        id: 37,
        no_tiket: "TKT-00037",
        cid: "3637383940",
        nama: "Toby Green",
        alamat: "Jl. Contoh No. 37, Surabaya",
        no_hp: "117890123456",
        komplain: "Sinyal lemah",
        pelapor: "Toby Green",
        tanggal_laporan: "2023-11-06",
        status: "Close",
        jenis_gangguan: "Network",
        jenis_perbaikan: "Perbaikan jaringan",
        lokasi_odp: "ODP 19",
        lokasi_closure: "Location S",
        jarak_kabel: "15m",
        redaman_terakhir: "4dB",
        nama_wifi: "WiFi-Toby",
        password_wifi: "toby123",
        keterangan: "Perbaikan selesai",
        tanggal_perbaikan: "2023-11-07",
        teknisi: "Teknisi R",
        createdAt: "2023-11-06",
        updatedAt: "2023-11-07"
    },
    {
        id: 38,
        no_tiket: "TKT-00038",
        cid: "4142434445",
        nama: "Uma Blue",
        alamat: "Jl. Contoh No. 38, Yogyakarta",
        no_hp: "118901234567",
        komplain: "Koneksi terputus-putus",
        pelapor: "Uma Blue",
        tanggal_laporan: "2023-11-07",
        status: "Open",
        jenis_gangguan: "Hardware",
        jenis_perbaikan: "",
        lokasi_odp: "",
        lokasi_closure: "",
        jarak_kabel: "",
        redaman_terakhir: "",
        nama_wifi: "",
        password_wifi: "",
        keterangan: "",
        tanggal_perbaikan: "",
        teknisi: "",
        createdAt: "2023-11-07",
        updatedAt: "2023-11-08"
    },
    {
        id: 39,
        no_tiket: "TKT-00039",
        cid: "4647484950",
        nama: "Vera Red",
        alamat: "Jl. Contoh No. 39, Jakarta",
        no_hp: "119012345678",
        komplain: "Internet lambat",
        pelapor: "Vera Red",
        tanggal_laporan: "2023-11-08",
        status: "Close",
        jenis_gangguan: "Network",
        jenis_perbaikan: "Reset",
        lokasi_odp: "ODP 20",
        lokasi_closure: "Location T",
        jarak_kabel: "20m",
        redaman_terakhir: "5dB",
        nama_wifi: "WiFi-Vera",
        password_wifi: "verapassword",
        keterangan: "Perbaikan selesai",
        tanggal_perbaikan: "2023-11-09",
        teknisi: "Teknisi S",
        createdAt: "2023-11-08",
        updatedAt: "2023-11-09"
    },
    {
        id: 40,
        no_tiket: "TKT-00040",
        cid: "5152535455",
        nama: "Wendy Green",
        alamat: "Jl. Contoh No. 40, Bandung",
        no_hp: "120123456789",
        komplain: "Tidak bisa login",
        pelapor: "Wendy Green",
        tanggal_laporan: "2023-11-09",
        status: "Open",
        jenis_gangguan: "Software",
        jenis_perbaikan: "",
        lokasi_odp: "",
        lokasi_closure: "",
        jarak_kabel: "",
        redaman_terakhir: "",
        nama_wifi: "",
        password_wifi: "",
        keterangan: "",
        tanggal_perbaikan: "",
        teknisi: "",
        createdAt: "2023-11-09",
        updatedAt: "2023-11-10"
    },
    {
        id: 41,
        no_tiket: "TKT-00041",
        cid: "6061626364",
        nama: "Xander Blue",
        alamat: "Jl. Contoh No. 41, Surabaya",
        no_hp: "121234567890",
        komplain: "Sinyal lemah",
        pelapor: "Xander Blue",
        tanggal_laporan: "2023-11-10",
        status: "Close",
        jenis_gangguan: "Network",
        jenis_perbaikan: "Perbaikan jaringan",
        lokasi_odp: "ODP 21",
        lokasi_closure: "Location U",
        jarak_kabel: "15m",
        redaman_terakhir: "4dB",
        nama_wifi: "WiFi-Xander",
        password_wifi: "xanderpassword",
        keterangan: "Perbaikan selesai",
        tanggal_perbaikan: "2023-11-11",
        teknisi: "Teknisi T",
        createdAt: "2023-11-10",
        updatedAt: "2023-11-11"
    },
    {
        id: 42,
        no_tiket: "TKT-00042",
        cid: "7071727374",
        nama: "Yara Red",
        alamat: "Jl. Contoh No. 42, Yogyakarta",
        no_hp: "122345678901",
        komplain: "Koneksi terputus-putus",
        pelapor: "Yara Red",
        tanggal_laporan: "2023-11-11",
        status: "Open",
        jenis_gangguan: "Hardware",
        jenis_perbaikan: "",
        lokasi_odp: "",
        lokasi_closure: "",
        jarak_kabel: "",
        redaman_terakhir: "",
        nama_wifi: "",
        password_wifi: "",
        keterangan: "",
        tanggal_perbaikan: "",
        teknisi: "",
        createdAt: "2023-11-11",
        updatedAt: "2023-11-12"
    },
    {
        id: 43,
        no_tiket: "TKT-00043",
        cid: "8081828384",
        nama: "Zane Black",
        alamat: "Jl. Contoh No. 43, Jakarta",
        no_hp: "123456789012",
        komplain: "Internet lambat",
        pelapor: "Zane Black",
        tanggal_laporan: "2023-11-12",
        status: "Close",
        jenis_gangguan: "Network",
        jenis_perbaikan: "Reset",
        lokasi_odp: "ODP 22",
        lokasi_closure: "Location V",
        jarak_kabel: "20m",
        redaman_terakhir: "5dB",
        nama_wifi: "WiFi-Zane",
        password_wifi: "zane123",
        keterangan: "Perbaikan selesai",
        tanggal_perbaikan: "2023-11-13",
        teknisi: "Teknisi U",
        createdAt: "2023-11-12",
        updatedAt: "2023-11-13"
    },
    {
        id: 44,
        no_tiket: "TKT-00044",
        cid: "9091929394",
        nama: "Ava Green",
        alamat: "Jl. Contoh No. 44, Bandung",
        no_hp: "124567890123",
        komplain: "Tidak bisa login",
        pelapor: "Ava Green",
        tanggal_laporan: "2023-11-13",
        status: "Open",
        jenis_gangguan: "Software",
        jenis_perbaikan: "",
        lokasi_odp: "",
        lokasi_closure: "",
        jarak_kabel: "",
        redaman_terakhir: "",
        nama_wifi: "",
        password_wifi: "",
        keterangan: "",
        tanggal_perbaikan: "",
        teknisi: "",
        createdAt: "2023-11-13",
        updatedAt: "2023-11-14"
    },
    {
        id: 45,
        no_tiket: "TKT-00045",
        cid: "1011121314",
        nama: "Liam Blue",
        alamat: "Jl. Contoh No. 45, Surabaya",
        no_hp: "125678901234",
        komplain: "Sinyal lemah",
        pelapor: "Liam Blue",
        tanggal_laporan: "2023-11-14",
        status: "Close",
        jenis_gangguan: "Network",
        jenis_perbaikan: "Perbaikan jaringan",
        lokasi_odp: "ODP 23",
        lokasi_closure: "Location W",
        jarak_kabel: "15m",
        redaman_terakhir: "4dB",
        nama_wifi: "WiFi-Liam",
        password_wifi: "liam123",
        keterangan: "Perbaikan selesai",
        tanggal_perbaikan: "2023-11-15",
        teknisi: "Teknisi V",
        createdAt: "2023-11-14",
        updatedAt: "2023-11-15"
    },
    {
        id: 46,
        no_tiket: "TKT-00046",
        cid: "1314151617",
        nama: "Mason Red",
        alamat: "Jl. Contoh No. 46, Yogyakarta",
        no_hp: "126789012345",
        komplain: "Koneksi terputus-putus",
        pelapor: "Mason Red",
        tanggal_laporan: "2023-11-15",
        status: "Open",
        jenis_gangguan: "Hardware",
        jenis_perbaikan: "",
        lokasi_odp: "",
        lokasi_closure: "",
        jarak_kabel: "",
        redaman_terakhir: "",
        nama_wifi: "",
        password_wifi: "",
        keterangan: "",
        tanggal_perbaikan: "",
        teknisi: "",
        createdAt: "2023-11-15",
        updatedAt: "2023-11-16"
    },
    {
        id: 47,
        no_tiket: "TKT-00047",
        cid: "1819202122",
        nama: "Nora Green",
        alamat: "Jl. Contoh No. 47, Jakarta",
        no_hp: "127890123456",
        komplain: "Internet lambat",
        pelapor: "Nora Green",
        tanggal_laporan: "2023-11-16",
        status: "Close",
        jenis_gangguan: "Network",
        jenis_perbaikan: "Reset",
        lokasi_odp: "ODP 24",
        lokasi_closure: "Location X",
        jarak_kabel: "20m",
        redaman_terakhir: "5dB",
        nama_wifi: "WiFi-Nora",
        password_wifi: "nora123",
        keterangan: "Perbaikan selesai",
        tanggal_perbaikan: "2023-11-17",
        teknisi: "Teknisi W",
        createdAt: "2023-11-16",
        updatedAt: "2023-11-17"
    },
    {
        id: 48,
        no_tiket: "TKT-00048",
        cid: "2223242526",
        nama: "Oscar Blue",
        alamat: "Jl. Contoh No. 48, Bandung",
        no_hp: "128901234567",
        komplain: "Tidak bisa login",
        pelapor: "Oscar Blue",
        tanggal_laporan: "2023-11-17",
        status: "Open",
        jenis_gangguan: "Software",
        jenis_perbaikan: "",
        lokasi_odp: "",
        lokasi_closure: "",
        jarak_kabel: "",
        redaman_terakhir: "",
        nama_wifi: "",
        password_wifi: "",
        keterangan: "",
        tanggal_perbaikan: "",
        teknisi: "",
        createdAt: "2023-11-17",
        updatedAt: "2023-11-18"
    },
    {
        id: 49,
        no_tiket: "TKT-00049",
        cid: "2728293031",
        nama: "Piper Red",
        alamat: "Jl. Contoh No. 49, Surabaya",
        no_hp: "129012345678",
        komplain: "Sinyal lemah",
        pelapor: "Piper Red",
        tanggal_laporan: "2023-11-18",
        status: "Close",
        jenis_gangguan: "Network",
        jenis_perbaikan: "Perbaikan jaringan",
        lokasi_odp: "ODP 25",
        lokasi_closure: "Location Y",
        jarak_kabel: "15m",
        redaman_terakhir: "4dB",
        nama_wifi: "WiFi-Piper",
        password_wifi: "piper123",
        keterangan: "Perbaikan selesai",
        tanggal_perbaikan: "2023-11-19",
        teknisi: "Teknisi X",
        createdAt: "2023-11-18",
        updatedAt: "2023-11-19"
    },
    {
        id: 50,
        no_tiket: "TKT-00050",
        cid: "3233343536",
        nama: "Quincy Green",
        alamat: "Jl. Contoh No. 50, Yogyakarta",
        no_hp: "130123456789",
        komplain: "Koneksi terputus-putus",
        pelapor: "Quincy Green",
        tanggal_laporan: "2023-11-19",
        status: "Open",
        jenis_gangguan: "Hardware",
        jenis_perbaikan: "",
        lokasi_odp: "",
        lokasi_closure: "",
        jarak_kabel: "",
        redaman_terakhir: "",
        nama_wifi: "",
        password_wifi: "",
        keterangan: "",
        tanggal_perbaikan: "",
        teknisi: "",
        createdAt: "2023-11-19",
        updatedAt: "2023-11-20"
    }
];

module.exports = dummyData; 